/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 store1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/store1.glb')
  return (
    <group {...props} dispose={null} >
      <mesh receiveShadow castShadow geometry={nodes.Building.geometry} material={nodes.Building.material} position={[0, 3.013, 0]} scale={[6, 3, 12.081]} />
      <mesh receiveShadow castShadow geometry={nodes.Door.geometry} material={nodes.Door.material} position={[5.118, 2.819, 13.494]} rotation={[0, 0.528, 0]} />
      <mesh receiveShadow castShadow geometry={nodes.Register.geometry} material={nodes.Register.material} position={[0.233, 1.117, -3.029]} />
      <mesh receiveShadow castShadow geometry={nodes['Stand_(Side)001'].geometry} material={nodes['Stand_(Side)001'].material} position={[-8.59, 1.261, 5.591]} />
      <mesh receiveShadow castShadow geometry={nodes['Stand_(Center)'].geometry} material={nodes['Stand_(Center)'].material} position={[0, 2.686, 4.629]} />
      <mesh receiveShadow castShadow geometry={nodes['Stand_(Side)'].geometry} material={nodes['Stand_(Side)'].material} position={[-0.14, 0, 5.128]} />
      <mesh receiveShadow castShadow geometry={nodes.Cash_Register.geometry} material={nodes.Cash_Register.material} position={[-3.231, 2.769, -3.023]} />
      <mesh receiveShadow castShadow geometry={nodes.Plane.geometry} material={nodes.Plane.material} />
      <mesh receiveShadow castShadow geometry={nodes.Trotoar.geometry} material={nodes.Trotoar.material} position={[-27.88, -0.479, 23.296]} scale={[0.556, 0.492, 0.556]} />
      <mesh receiveShadow castShadow geometry={nodes.Tiang.geometry} material={nodes.Tiang.material} position={[-25.832, 3.537, 19.602]} scale={0.822} />
      <mesh receiveShadow castShadow geometry={nodes.LampFrame.geometry} material={materials['Material.006']} position={[-25.832, 7.968, 19.59]} scale={0.822} />
      <mesh receiveShadow castShadow geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[-25.832, 6.698, 19.601]} scale={0.822} />
      <mesh receiveShadow castShadow geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} position={[0, -0.728, 37.562]} scale={[1, 1, 2.631]} />
      <mesh receiveShadow castShadow geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[0, 0, -47.513]} scale={[1, 1, 2.631]} />
      <mesh receiveShadow castShadow geometry={nodes.Trotoar001.geometry} material={nodes.Trotoar001.material} position={[27.255, -0.479, 51.829]} rotation={[Math.PI, 0, Math.PI]} scale={[0.556, 0.492, 0.556]} />
      <mesh receiveShadow castShadow geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} position={[0, -0.479, 57.595]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh receiveShadow castShadow geometry={nodes.Cube.geometry} material={materials['Material.002']} />
      <mesh receiveShadow castShadow geometry={nodes.Cube001.geometry} material={materials['Material.002']} position={[-0.272, 20.974, 72.339]} scale={[7.949, 8.059, 7.949]} />
      <mesh receiveShadow castShadow geometry={nodes.Cube005.geometry} material={materials['Material.005']} position={[-22.887, 0, 0]} scale={[1, 1.308, 1]} />
      <mesh receiveShadow castShadow geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[-13.999, 1.145, 13.765]} scale={[0.081, 0.149, 0.022]} />
      <mesh receiveShadow castShadow geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[25.523, 1.145, 13.765]} scale={[0.081, 0.149, 0.022]} />
      <mesh receiveShadow castShadow geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} />
      <mesh receiveShadow castShadow geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[11.909, 1.007, 22.356]} rotation={[0, -Math.PI / 2, 0]} scale={[0.271, 1, 0.271]} />
      <mesh receiveShadow castShadow geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[11.909, 7.922, 22.356]} rotation={[0, -Math.PI / 2, 0]} scale={0.148} />
      <mesh receiveShadow castShadow geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[11.909, 7.695, 22.356]} rotation={[0, -Math.PI / 2, 0]} scale={[0.156, 0.079, 0.156]} />
      <mesh receiveShadow castShadow geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[11.752, 6.688, 22.335]} rotation={[0, -Math.PI / 2, 0]} scale={[0.736, 0.736, 0.457]} />
      <mesh receiveShadow castShadow geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[34.45, 0, 7.552]} />
    </group>
  )
}

export default Model

useGLTF.preload('/store1.glb')
